/** Registry for all overworld building definitions in the game */

import { BuildingDefinition } from '../buildings/BuildingDefinition.js';

export class BuildingRegistry {
  private static buildings = new Map<string, BuildingDefinition>([
    ['pokecenter', {
      id: 'pokecenter',
      name: 'Monster Healing Center',
      type: 'healing_center',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#cc2222',
      wallColor: '#ffffff',
      trimColor: '#e74c3c',
      roofStyle: 'sloped',
      signSymbol: 'P',
      signText: 'MONSTER CENTER',
      interiorMapId: 'pokecenter_interior',
      interiorSpawnTile: { x: 7, y: 8 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['pokemart', {
      id: 'pokemart',
      name: 'Supply Mart & Shop',
      type: 'shop',
      widthTiles: 4,
      heightTiles: 4,
      doorOffsetX: 1,
      doorOffsetY: 3,
      roofColor: '#2980b9',
      wallColor: '#ffffff',
      trimColor: '#3498db',
      roofStyle: 'sloped',
      signSymbol: 'M',
      signText: 'MART',
      interiorMapId: 'pokemart_interior',
      interiorSpawnTile: { x: 5, y: 7 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['lab', {
      id: 'lab',
      name: 'Research Lab',
      type: 'lab',
      widthTiles: 6,
      heightTiles: 4,
      doorOffsetX: 3,
      doorOffsetY: 3,
      roofColor: '#16a085',
      wallColor: '#f8f9fa',
      trimColor: '#1abc9c',
      roofStyle: 'glass',
      signSymbol: '⚛',
      signText: 'RESEARCH LAB',
      interiorMapId: 'lab_interior',
      interiorSpawnTile: { x: 7, y: 9 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['warehouse', {
      id: 'warehouse',
      name: 'Cargo Warehouse',
      type: 'warehouse',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#5d6d7e',
      wallColor: '#abb2b9',
      trimColor: '#34495e',
      roofStyle: 'flat',
      signSymbol: '📦',
      signText: 'WAREHOUSE',
      interiorMapId: 'warehouse_interior',
      interiorSpawnTile: { x: 6, y: 8 },
      interiorSpawnDirection: 'up',
    }],
    ['inn', {
      id: 'inn',
      name: 'Traveler\'s Inn',
      type: 'inn',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#8e44ad',
      wallColor: '#f5eef8',
      trimColor: '#9b59b6',
      roofStyle: 'peaked',
      signSymbol: '🛌',
      signText: 'INN & LODGE',
      interiorMapId: 'inn_interior',
      interiorSpawnTile: { x: 6, y: 8 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['ranger_station', {
      id: 'ranger_station',
      name: 'Wilderness Ranger Station',
      type: 'ranger_station',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#27ae60',
      wallColor: '#e8f8f5',
      trimColor: '#2eabe2',
      roofStyle: 'sloped',
      signSymbol: '🛡',
      signText: 'RANGER OUTPOST',
      interiorMapId: 'ranger_interior',
      interiorSpawnTile: { x: 6, y: 8 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['windmill', {
      id: 'windmill',
      name: 'Old Valley Windmill',
      type: 'windmill',
      widthTiles: 4,
      heightTiles: 5,
      doorOffsetX: 1,
      doorOffsetY: 4,
      roofColor: '#a04000',
      wallColor: '#fdfefe',
      trimColor: '#d35400',
      roofStyle: 'windmill',
      signSymbol: '⚙',
      signText: 'WINDMILL COTTAGE',
      interiorMapId: 'windmill_interior',
      interiorSpawnTile: { x: 5, y: 7 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['house_small', {
      id: 'house_small',
      name: 'Cozy Residence',
      type: 'house',
      widthTiles: 4,
      heightTiles: 3,
      doorOffsetX: 1,
      doorOffsetY: 2,
      roofColor: '#8b4513',
      wallColor: '#f5f5dc',
      trimColor: '#5c3a21',
      roofStyle: 'peaked',
      interiorMapId: 'house_001_interior',
      interiorSpawnTile: { x: 5, y: 6 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['manor', {
      id: 'manor',
      name: 'Mayor\'s Grand Manor',
      type: 'manor',
      widthTiles: 6,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#2c3e50',
      wallColor: '#ecf0f1',
      trimColor: '#34495e',
      roofStyle: 'peaked',
      signSymbol: '👑',
      signText: 'TOWN MANOR',
      interiorMapId: 'manor_interior',
      interiorSpawnTile: { x: 7, y: 8 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['boutique', {
      id: 'boutique',
      name: 'Fashion Stylist Boutique',
      type: 'boutique',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#e84393',
      wallColor: '#fd79a8',
      trimColor: '#d63031',
      roofStyle: 'peaked',
      signSymbol: '✂',
      signText: 'OUTFIT STYLIST',
      interiorMapId: 'boutique_interior',
      interiorSpawnTile: { x: 6, y: 8 },
      interiorSpawnDirection: 'up',
      animated: true,
    }],
    ['library', {
      id: 'library',
      name: 'City Grand Library',
      type: 'library',
      widthTiles: 5,
      heightTiles: 4,
      doorOffsetX: 2,
      doorOffsetY: 3,
      roofColor: '#d35400',
      wallColor: '#fef5e7',
      trimColor: '#e67e22',
      roofStyle: 'sloped',
      signSymbol: '📖',
      signText: 'CITY LIBRARY',
      interiorMapId: 'library_interior',
      interiorSpawnTile: { x: 6, y: 8 },
      interiorSpawnDirection: 'up',
    }],
    ['collector', {
      id: 'collector',
      name: 'Collector\'s Haven',
      type: 'house',
      widthTiles: 4,
      heightTiles: 3,
      doorOffsetX: 2,
      doorOffsetY: 2,
      roofColor: '#27ae60',
      wallColor: '#f4f6f7',
      trimColor: '#1e8449',
      roofStyle: 'peaked',
      signSymbol: '💎',
      signText: 'COLLECTOR',
      interiorMapId: 'collector_interior',
      interiorSpawnTile: { x: 5, y: 6 },
      interiorSpawnDirection: 'up',
    }],
  ]);

  public static get(id: string): BuildingDefinition | undefined {
    return this.buildings.get(id);
  }

  public static register(def: BuildingDefinition): void {
    this.buildings.set(def.id, def);
  }

  public static getAll(): BuildingDefinition[] {
    return Array.from(this.buildings.values());
  }
}
